# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [2]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)


In [4]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [6]:
# Checking the dimensions of the array
arr_3.ndim

2

In [7]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [10]:
# Creating an array of first ten natural numbers
arr_4 = np.array(range(1, 11*12+1))

# Printing the created array
arr_4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132])

In [11]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
np.unravel_index(99, (11,12))

(8, 3)

In [13]:
# Checking the rows and columns in the created array
arr_5 = [[1, 5],
 [3, 7],
 [4, 9]]

np.reshape(arr_5, -1)

array([1, 5, 3, 7, 4, 9])

In [15]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = [[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],]

# Checking the rows and columns in the created array


In [16]:
# Stacking arr_5 and arr_6
arr_6

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

In [19]:
# Check the structure of arr_6
print(arr_6[arr_6%2 != 0].reshape(5, 2))

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [ ]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = 
arr_6

In [ ]:
# Stacking arr_5 and arr_6


In [20]:
arr_6[arr_6 %2 != 0]

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [22]:
p = [[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p,(1,-1))

array([[1, 5, 3, 7, 4, 9]])